{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMFq6LfniNT/3IzZF1iNEZn",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/aryzuqnil-dev/gdp-dashboard/blob/main/science_quiz.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "assCs-OijU2I"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "\n",
        "# -----------------------------\n",
        "# PAGE CONFIGURATION\n",
        "# -----------------------------\n",
        "st.set_page_config(\n",
        "    page_title=\"Year 5 Science Quiz\",\n",
        "    page_icon=\"🔬\",\n",
        "    layout=\"centered\"\n",
        ")\n",
        "\n",
        "# -----------------------------\n",
        "# TITLE\n",
        "# -----------------------------\n",
        "st.title(\"🔬 Year 5 Science Quiz\")\n",
        "st.subheader(\"Test Your Science Knowledge!\")\n",
        "\n",
        "st.write(\n",
        "    \"Answer all 10 questions. Choose the best answer for each question \"\n",
        "    \"and click **Submit Quiz** when you are finished.\"\n",
        ")\n",
        "\n",
        "st.divider()\n",
        "\n",
        "# -----------------------------\n",
        "# QUIZ QUESTIONS\n",
        "# -----------------------------\n",
        "questions = [\n",
        "    {\n",
        "        \"question\": \"1. Which part of a plant absorbs water from the soil?\",\n",
        "        \"options\": [\"Leaves\", \"Roots\", \"Flowers\", \"Fruits\"],\n",
        "        \"answer\": \"Roots\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"2. Which organ pumps blood around the human body?\",\n",
        "        \"options\": [\"Brain\", \"Lungs\", \"Heart\", \"Stomach\"],\n",
        "        \"answer\": \"Heart\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"3. Which state of matter has a fixed shape and fixed volume?\",\n",
        "        \"options\": [\"Solid\", \"Liquid\", \"Gas\", \"Water vapour\"],\n",
        "        \"answer\": \"Solid\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"4. What happens to water when it is heated until it boils?\",\n",
        "        \"options\": [\n",
        "            \"It freezes\",\n",
        "            \"It becomes water vapour\",\n",
        "            \"It becomes ice\",\n",
        "            \"It becomes soil\"\n",
        "        ],\n",
        "        \"answer\": \"It becomes water vapour\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"5. Which planet do we live on?\",\n",
        "        \"options\": [\"Mars\", \"Venus\", \"Earth\", \"Jupiter\"],\n",
        "        \"answer\": \"Earth\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"6. What is the main source of energy for Earth?\",\n",
        "        \"options\": [\"The Moon\", \"The Sun\", \"The stars\", \"The ocean\"],\n",
        "        \"answer\": \"The Sun\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"7. Which animal is a vertebrate?\",\n",
        "        \"options\": [\"Earthworm\", \"Butterfly\", \"Fish\", \"Jellyfish\"],\n",
        "        \"answer\": \"Fish\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"8. Which force pulls objects toward Earth?\",\n",
        "        \"options\": [\"Magnetism\", \"Gravity\", \"Friction\", \"Electricity\"],\n",
        "        \"answer\": \"Gravity\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"9. Which gas do humans need for respiration?\",\n",
        "        \"options\": [\"Carbon dioxide\", \"Nitrogen\", \"Oxygen\", \"Helium\"],\n",
        "        \"answer\": \"Oxygen\"\n",
        "    },\n",
        "    {\n",
        "        \"question\": \"10. What process changes liquid water into water vapour?\",\n",
        "        \"options\": [\n",
        "            \"Condensation\",\n",
        "            \"Freezing\",\n",
        "            \"Evaporation\",\n",
        "            \"Melting\"\n",
        "        ],\n",
        "        \"answer\": \"Evaporation\"\n",
        "    }\n",
        "]\n",
        "\n",
        "# -----------------------------\n",
        "# SESSION STATE\n",
        "# -----------------------------\n",
        "if \"submitted\" not in st.session_state:\n",
        "    st.session_state.submitted = False\n",
        "\n",
        "# -----------------------------\n",
        "# DISPLAY QUESTIONS\n",
        "# -----------------------------\n",
        "student_answers = []\n",
        "\n",
        "for i, q in enumerate(questions):\n",
        "\n",
        "    st.markdown(f\"### {q['question']}\")\n",
        "\n",
        "    answer = st.radio(\n",
        "        \"Choose your answer:\",\n",
        "        q[\"options\"],\n",
        "        index=None,\n",
        "        key=f\"question_{i}\"\n",
        "    )\n",
        "\n",
        "    student_answers.append(answer)\n",
        "\n",
        "    st.write(\"\")\n",
        "\n",
        "# -----------------------------\n",
        "# SUBMIT BUTTON\n",
        "# -----------------------------\n",
        "if st.button(\"✅ Submit Quiz\", type=\"primary\", use_container_width=True):\n",
        "\n",
        "    # Check whether all questions are answered\n",
        "    if None in student_answers:\n",
        "\n",
        "        st.warning(\n",
        "            \"⚠️ Please answer all questions before submitting the quiz.\"\n",
        "        )\n",
        "\n",
        "    else:\n",
        "\n",
        "        st.session_state.submitted = True\n",
        "\n",
        "        score = 0\n",
        "\n",
        "        for i, q in enumerate(questions):\n",
        "\n",
        "            if student_answers[i] == q[\"answer\"]:\n",
        "                score += 1\n",
        "\n",
        "        percentage = (score / len(questions)) * 100\n",
        "\n",
        "        st.divider()\n",
        "\n",
        "        st.header(\"🎯 Quiz Result\")\n",
        "\n",
        "        col1, col2 = st.columns(2)\n",
        "\n",
        "        with col1:\n",
        "            st.metric(\n",
        "                label=\"Score\",\n",
        "                value=f\"{score}/{len(questions)}\"\n",
        "            )\n",
        "\n",
        "        with col2:\n",
        "            st.metric(\n",
        "                label=\"Percentage\",\n",
        "                value=f\"{percentage:.0f}%\"\n",
        "            )\n",
        "\n",
        "        # -----------------------------\n",
        "        # FEEDBACK\n",
        "        # -----------------------------\n",
        "        if percentage == 100:\n",
        "\n",
        "            st.success(\n",
        "                \"🌟 Excellent! Perfect score! \"\n",
        "                \"You are a Science Superstar!\"\n",
        "            )\n",
        "\n",
        "            st.balloons()\n",
        "\n",
        "        elif percentage >= 80:\n",
        "\n",
        "            st.success(\n",
        "                \"👏 Great job! You have a very good understanding of science.\"\n",
        "            )\n",
        "\n",
        "        elif percentage >= 60:\n",
        "\n",
        "            st.info(\n",
        "                \"👍 Good work! Keep practising and learning.\"\n",
        "            )\n",
        "\n",
        "        else:\n",
        "\n",
        "            st.warning(\n",
        "                \"📚 Keep learning! Review the science topics and try again.\"\n",
        "            )\n",
        "\n",
        "        # -----------------------------\n",
        "        # ANSWER REVIEW\n",
        "        # -----------------------------\n",
        "        st.divider()\n",
        "\n",
        "        st.header(\"📝 Answer Review\")\n",
        "\n",
        "        for i, q in enumerate(questions):\n",
        "\n",
        "            student_answer = student_answers[i]\n",
        "\n",
        "            if student_answer == q[\"answer\"]:\n",
        "\n",
        "                st.success(\n",
        "                    f\"{q['question']}\\n\\n\"\n",
        "                    f\"Your answer: {student_answer} ✅\"\n",
        "                )\n",
        "\n",
        "            else:\n",
        "\n",
        "                st.error(\n",
        "                    f\"{q['question']}\\n\\n\"\n",
        "                    f\"Your answer: {student_answer} ❌\\n\\n\"\n",
        "                    f\"Correct answer: {q['answer']}\"\n",
        "                )\n",
        "\n",
        "# -----------------------------\n",
        "# RESTART QUIZ\n",
        "# -----------------------------\n",
        "st.divider()\n",
        "\n",
        "if st.button(\"🔄 Restart Quiz\", use_container_width=True):\n",
        "\n",
        "    for key in list(st.session_state.keys):\n",
        "        del st.session_state[key]\n",
        "\n",
        "    st.rerun()\n",
        "\n",
        "# -----------------------------\n",
        "# FOOTER\n",
        "# -----------------------------\n",
        "st.caption(\n",
        "    \"Year 5 Science Interactive Quiz | Learning Science Through Technology\"\n",
        ")"
      ]
    }
  ]
}