# -*- coding: utf-8 -*-
"""science quiz

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ALsa2-b3f4fULdVxR-j1p_zTXn6khLuf
"""

import streamlit as st

# -----------------------------
# PAGE CONFIGURATION
# -----------------------------
st.set_page_config(
    page_title="Year 5 Science Quiz",
    page_icon="🔬",
    layout="centered"
)

# -----------------------------
# TITLE
# -----------------------------
st.title("🔬 Year 5 Science Quiz")
st.subheader("Test Your Science Knowledge!")

st.write(
    "Answer all 10 questions. Choose the best answer for each question "
    "and click **Submit Quiz** when you are finished."
)

st.divider()

# -----------------------------
# QUIZ QUESTIONS
# -----------------------------
questions = [
    {
        "question": "1. Which part of a plant absorbs water from the soil?",
        "options": ["Leaves", "Roots", "Flowers", "Fruits"],
        "answer": "Roots"
    },
    {
        "question": "2. Which organ pumps blood around the human body?",
        "options": ["Brain", "Lungs", "Heart", "Stomach"],
        "answer": "Heart"
    },
    {
        "question": "3. Which state of matter has a fixed shape and fixed volume?",
        "options": ["Solid", "Liquid", "Gas", "Water vapour"],
        "answer": "Solid"
    },
    {
        "question": "4. What happens to water when it is heated until it boils?",
        "options": [
            "It freezes",
            "It becomes water vapour",
            "It becomes ice",
            "It becomes soil"
        ],
        "answer": "It becomes water vapour"
    },
    {
        "question": "5. Which planet do we live on?",
        "options": ["Mars", "Venus", "Earth", "Jupiter"],
        "answer": "Earth"
    },
    {
        "question": "6. What is the main source of energy for Earth?",
        "options": ["The Moon", "The Sun", "The stars", "The ocean"],
        "answer": "The Sun"
    },
    {
        "question": "7. Which animal is a vertebrate?",
        "options": ["Earthworm", "Butterfly", "Fish", "Jellyfish"],
        "answer": "Fish"
    },
    {
        "question": "8. Which force pulls objects toward Earth?",
        "options": ["Magnetism", "Gravity", "Friction", "Electricity"],
        "answer": "Gravity"
    },
    {
        "question": "9. Which gas do humans need for respiration?",
        "options": ["Carbon dioxide", "Nitrogen", "Oxygen", "Helium"],
        "answer": "Oxygen"
    },
    {
        "question": "10. What process changes liquid water into water vapour?",
        "options": [
            "Condensation",
            "Freezing",
            "Evaporation",
            "Melting"
        ],
        "answer": "Evaporation"
    }
]

# -----------------------------
# SESSION STATE
# -----------------------------
if "submitted" not in st.session_state:
    st.session_state.submitted = False

# -----------------------------
# DISPLAY QUESTIONS
# -----------------------------
student_answers = []

for i, q in enumerate(questions):

    st.markdown(f"### {q['question']}")

    answer = st.radio(
        "Choose your answer:",
        q["options"],
        index=None,
        key=f"question_{i}"
    )

    student_answers.append(answer)

    st.write("")

# -----------------------------
# SUBMIT BUTTON
# -----------------------------
if st.button("✅ Submit Quiz", type="primary", use_container_width=True):

    # Check whether all questions are answered
    if None in student_answers:

        st.warning(
            "⚠️ Please answer all questions before submitting the quiz."
        )

    else:

        st.session_state.submitted = True

        score = 0

        for i, q in enumerate(questions):

            if student_answers[i] == q["answer"]:
                score += 1

        percentage = (score / len(questions)) * 100

        st.divider()

        st.header("🎯 Quiz Result")

        col1, col2 = st.columns(2)

        with col1:
            st.metric(
                label="Score",
                value=f"{score}/{len(questions)}"
            )

        with col2:
            st.metric(
                label="Percentage",
                value=f"{percentage:.0f}%"
            )

        # -----------------------------
        # FEEDBACK
        # -----------------------------
        if percentage == 100:

            st.success(
                "🌟 Excellent! Perfect score! "
                "You are a Science Superstar!"
            )

            st.balloons()

        elif percentage >= 80:

            st.success(
                "👏 Great job! You have a very good understanding of science."
            )

        elif percentage >= 60:

            st.info(
                "👍 Good work! Keep practising and learning."
            )

        else:

            st.warning(
                "📚 Keep learning! Review the science topics and try again."
            )

        # -----------------------------
        # ANSWER REVIEW
        # -----------------------------
        st.divider()

        st.header("📝 Answer Review")

        for i, q in enumerate(questions):

            student_answer = student_answers[i]

            if student_answer == q["answer"]:

                st.success(
                    f"{q['question']}\n\n"
                    f"Your answer: {student_answer} ✅"
                )

            else:

                st.error(
                    f"{q['question']}\n\n"
                    f"Your answer: {student_answer} ❌\n\n"
                    f"Correct answer: {q['answer']}"
                )

# -----------------------------
# RESTART QUIZ
# -----------------------------
st.divider()

if st.button("🔄 Restart Quiz", use_container_width=True):

    for key in list(st.session_state.keys):
        del st.session_state[key]

    st.rerun()

# -----------------------------
# FOOTER
# -----------------------------
st.caption(
    "Year 5 Science Interactive Quiz | Learning Science Through Technology"
)